// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $AgentConversation from "./islands/AgentConversation.tsx";
import * as $Carrosel from "./islands/Carrosel.tsx";
import * as $FutureCards from "./islands/FutureCards.tsx";
import * as $LanguageSwitcher from "./islands/LanguageSwitcher.tsx";
import * as $PlatformTabs from "./islands/PlatformTabs.tsx";
import * as $SACAgentTicket from "./islands/SACAgentTicket.tsx";
import * as $ServicesAccordion from "./islands/ServicesAccordion.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $TestimonialsCarousel from "./islands/TestimonialsCarousel.tsx";
import * as $VtexAgentChat from "./islands/VtexAgentChat.tsx";
import * as $WppConversation from "./islands/WppConversation.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AgentConversation.tsx": $AgentConversation,
    "./islands/Carrosel.tsx": $Carrosel,
    "./islands/FutureCards.tsx": $FutureCards,
    "./islands/LanguageSwitcher.tsx": $LanguageSwitcher,
    "./islands/PlatformTabs.tsx": $PlatformTabs,
    "./islands/SACAgentTicket.tsx": $SACAgentTicket,
    "./islands/ServicesAccordion.tsx": $ServicesAccordion,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/TestimonialsCarousel.tsx": $TestimonialsCarousel,
    "./islands/VtexAgentChat.tsx": $VtexAgentChat,
    "./islands/WppConversation.tsx": $WppConversation,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
