// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $ServicesAccordion from "./islands/ServicesAccordion.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ServicesAccordion.tsx": $ServicesAccordion,
    "./islands/SliderJS.tsx": $SliderJS,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
